language: python

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y jq

python:
  - 3.5

install:
  - pip install -r requirements.txt

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master

script:
  - bash ci.bash
