site_name: Subatomic
site_author: The Subatomic Team
site_description: Subatomic
copyright: '&copy; 2018 Subatomic Team'

# Configuration
theme:
  name: material
  logo: 'images/subatomic.svg'
  palette:
    primary: 'red'
    accent: 'red'

docs_dir: docs
google_analytics:
  - UA-107338053-1
  - auto
repo_name: absa-subatomic
repo_url: https://github.com/absa-subatomic/subatomic-documentation
extra:
  palette:
    primary: blue-grey
    accent: blue-grey
  social:
    - type: github
      link: https://github.com/absa-subatomic
pages:
- Home: index.md
- New to Subatomic: new-to-subatomic.md
- Quantum Mechanic: quantum-mechanic.md
